export const project = [
  
  {
    id: 7,
    username:"",
    password:"",
    title: "E-commerce Website",
    image: "/online.png",
    desc: "This is a protype online shopping website. This website is enhanced version of first project  E-commerce website UI where the simple HTML , CSS, javascript  version of ui is converted using Next.JS, tailwind CSS, typescript. The implementation of jwt authentication, Rest API is done and backend is created using NodeJS, Express and mongodb. ",
    githubLink: "https://github.com/parashe/OnlineShop.git",
    projectLink: "https://onlineshop-frontend.vercel.app/",
    techStack: [
      "NextJS",
      "Node.JS",
      "Express",
      "MongoDB",
      "HTML",
      "CSS",
      "tailwind CSS",
      "TypeScript",
      "Rest API",
    ],
  },
  {
    id: 8,
    username:"user@example.com",
    password:"User@123",
    title: "E-commerce Website ADmin Panel",
    image: "/admin.png",
    desc: "This is a admin panel for an online shopping website. The proper implementation of role using Context API and jwt authentication is done. This website is enhanced version of first project  E-commerce website UI where the simple HTML , CSS, javascript  version of ui is converted using Next.JS, tailwind CSS, typescript. The implementation of jwt authentication, Rest API is done and backend is created using NodeJS, Express and mongodb. ",
    githubLink: "https://github.com/parashe/OnlineShop.git",
    projectLink: "https://onlineshop-admin.vercel.app/",
    techStack: [
      "NextJS",
      "Node.JS",
      "Express",
      "MongoDB",
      "HTML",
      "CSS",
      "tailwind CSS",
      "TypeScript",
      "Rest API",
    ],

  },
  {
    id: 2,
    title: "Travel Website",
    image: "/amazing.png",
    username:"",
    password:"",
    desc: "This  website is currently in development. This contains only the user interface and not connected with the backednd. but it is designed using dummy data so that it can be connected and data can be displayed easily from backend if connected.This is Amazing Nepal  website build using React,Typescript and Tailwind CSS. ",
    githubLink: "https://github.com/parashe/amazingnepal.git",
    projectLink: "https://amazingnepal.vercel.app/",
    techStack: ["React", "TypeScript", "Tailwind CSS"],
  },
  {
    id: 1,
    username:"",
    password:"",
    title: "E-commerce Website UI",
    image: "/ecommerce-ui.png",
    desc: "This is an  simple user interface designed for an online shopping website. This website has a user-friendly interface with a clean and modern design.",
    githubLink: "https://github.com/exampleuser/ecommerce-website",
    projectLink: "https://parashe.github.io/Ecommerce_UI/html/index.html",
    techStack: ["Html", "CSS", "JavaScript"],
  },
  {
    id: 9,
    title: "Transpiler to Convert React Native Code to React",
    image: "/mobile.png",
    username:"",
    password:"",
    desc: "This transpiler convert React Native components into React components without needing the React Native for Web library. It uses Babel to create a structure called an Abstract Syntax Tree (AST) from the code and then changes JSX syntax into code that works on the web.",
    githubLink: "https://github.com/parashe/code-shared-app.git",
    projectLink: "/#",
    techStack: ["React","React Native","Transpiler","Babel", "Parcel", "AST"],
  },
  {
    id: 3,
    username:"",
    password:"",
    title: "Educational Consultancy Website",
    image: "/subedi.png",
    desc: "This website was built 3 years back for the educational consultancy website. An interactive and user-friendly website designed to provide comprehensive educational consultancy services. Our platform offers personalized guidance and support to students and parents seeking assistance with academic planning, career counseling, college admissions, and more. ",
    githubLink: "https://github.com/parashe/Subdei.git",
    projectLink: "https://subedi.vercel.app/",
    techStack: ["React", "CSS", "Material-UI", "Font Awesome", "Bootstrap"],
  },
  {
    id: 4,
    title: "Rotaract Club Website",
    image: "/rotaract.png",
    username:"",
    password:"",
    githubLink: "https://github.com/parashe/RotractNewWebsiteCode.git",
    projectLink: "https://rotaractitabhatta.vercel.app",
    desc: "This website was built 3 years back for the Rotaract Club Website based in Nepal, your gateway to the world of community service and volunteerism! This website is designed to connect members, showcase our projects, and promote our mission of service and leadership development. With a sleek and user-friendly interface built using React, CSS, Material-UI, and Font Awesome, navigating through our site is a breeze.",
    techStack: ["React", "CSS", "Material-UI", "Font Awesome", "Bootstrap"],
  },

  {
    id: 5,
    username:"",
    password:"",
    title: "Reusable Date Time Picker ",
    image: "/datepicker.png",
    githubLink: "https://github.com/parashe/DateTimePicker.git",
    projectLink: "https://date-time-picker-blush.vercel.app/",
    desc: "The DateTimepicker component is a React component that allows users to select date and time values using the Material-UI DateTimePicker. This component also includes functionality to handle date and time filtering and displays a loading spinner during searching.",
    techStack: ["NextJS", "Tailwind CSS", "TypeScript", "Material-UI", "CSS"],
  },
  {
    id: 6,
    username:"",
    password:"",
    title: "Multiple and Single Select Dropdown",
    image: "/dropdown.png",
    githubLink: "https://github.com/parashe/dropdown-selector.git",
    projectLink: "https://dropdown-selector-orpin.vercel.app/#",
    desc: "This is a  reusable component which is developed using NextJS and tailwind CSS. It includes multiple and single select dropdown.  This was built to show how we can use the mulitple select and single select dropdown. ",
    techStack: ["NextJS", "Tailwind CSS", "TypeScript", "CSS"],
  },
];
