export const project = [
  {
    id: 1,
    title: "E-commerce Website",
    image: "/onlineshop.png",
    desc: "An e-commerce website built with React and Node.js, featuring a user-friendly interface and secure payment gateway integration.An e-commerce website built with React and Node.js, featuring a user-friendly interface and secure payment gateway integration. An e-commerce website built with React and Node.js, featuring a user-friendly interface and secure payment gateway integration.",
    githubLink: "https://github.com/exampleuser/ecommerce-website",
    projectLink: "https://example.com/ecommerce",
    techStack: ["React", "Node.js", "Express", "MongoDB", "Stripe"],
  },
  {
    id: 2,
    title: "Task Management App",
    image: "/amazing.png",
    desc: "An e-commerce website built with React and Node.js, featuring a user-friendly interface and secure payment gateway integration.An e-commerce website built with React and Node.js, featuring a user-friendly interface and secure payment gateway integration. An e-commerce website built with React and Node.js, featuring a user-friendly interface and secure payment gateway integration.",
    githubLink: "https://github.com/exampleuser/task-management-app",
    projectLink: "https://example.com/task-management",
    techStack: ["React", "Firebase", "Material-UI"],
  },
  {
    id: 3,
    title: "E-commerce Website",
    image: "/onlineshop.png",
    desc: "An e-commerce website built with React and Node.js, featuring a user-friendly interface and secure payment gateway integration.An e-commerce website built with React and Node.js, featuring a user-friendly interface and secure payment gateway integration. An e-commerce website built with React and Node.js, featuring a user-friendly interface and secure payment gateway integration.",
    githubLink: "https://github.com/exampleuser/ecommerce-website",
    projectLink: "https://example.com/ecommerce",
    techStack: ["React", "Node.js", "Express", "MongoDB", "Stripe"],
  },
  {
    id: 4,
    title: "Task Management App",
    image: "/amazing.png",
    desc: "An e-commerce website built with React and Node.js, featuring a user-friendly interface and secure payment gateway integration.An e-commerce website built with React and Node.js, featuring a user-friendly interface and secure payment gateway integration. An e-commerce website built with React and Node.js, featuring a user-friendly interface and secure payment gateway integration.",
    githubLink: "https://github.com/exampleuser/task-management-app",
    projectLink: "https://example.com/task-management",
    techStack: ["React", "Firebase", "Material-UI"],
  },
  {
    id: 5,
    title: "E-commerce Website",
    image: "/onlineshop.png",
    desc: "An e-commerce website built with React and Node.js, featuring a user-friendly interface and secure payment gateway integration.An e-commerce website built with React and Node.js, featuring a user-friendly interface and secure payment gateway integration. An e-commerce website built with React and Node.js, featuring a user-friendly interface and secure payment gateway integration.",
    githubLink: "https://github.com/exampleuser/ecommerce-website",
    projectLink: "https://example.com/ecommerce",
    techStack: ["React", "Node.js", "Express", "MongoDB", "Stripe"],
  },
  {
    id: 6,
    title: "Task Management App",
    image: "/amazing.png",
    desc: "An e-commerce website built with React and Node.js, featuring a user-friendly interface and secure payment gateway integration.An e-commerce website built with React and Node.js, featuring a user-friendly interface and secure payment gateway integration. An e-commerce website built with React and Node.js, featuring a user-friendly interface and secure payment gateway integration.",
    githubLink: "https://github.com/exampleuser/task-management-app",
    projectLink: "https://example.com/task-management",
    techStack: ["React", "Firebase", "Material-UI"],
  },
];
